scrape_configs:
  - job_name: 'cluster-node'
    static_configs:
      - targets:
          - '10.158.3.228:9100'
          - '10.158.3.229:9100'
          - '10.158.3.230:9100'
          - '10.158.3.231:9100'
          - '10.158.3.232:9100'
